<?php

namespace PPESymfony\PPEBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChambreRepository extends EntityRepository
{
}
