<?php

namespace PPESymfony\PPEBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SejourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SejourRepository extends EntityRepository
{
}
